# Generated by Django 6.0.4 on 2026-04-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tag',
            field=models.CharField(default='Need', max_length=50),
            preserve_default=False,
        ),
    ]
